#theme: jekyll-theme-hacker
name: appfair.org
title: The App Fair Project
email: info@appfair.org

tagline: "The universal free and open-source app marketplace"

description: >-
  The App Fair Project provides a free and open-source marketplace for mobile apps

header_pages:
  #- title: "Home"
    #href: "/"
  #- title: "Create"
    #href: "/create/"

  - index.md
  - create/index.md
  - blog/index.md
  - donate/index.md
  # - marketplace/index.md
  
languages:
  - en
  - fr
  - es
  - pt
  - it
  - de
  - ru
  - ja
  - ko
  - zh-cn
  - zh-tw
  - ar

language_names:
  en: English
  fr: Français
  es: Español
  pt: Português
  it: Italiano
  de: Deutsch
  ru: Русский
  ja: 日本語
  ko: 한국어
  zh-cn: 简体中文
  zh-tw: 繁體中文
  ar: العربية

collections:
  posts:
    output: true
    permalink: /blog/:title
    source: _posts
    #layout: blog

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
